# -*- coding: utf-8 -*-
"""exerciciosII- Kauan Weslley - 3INFO2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Srpj7HDtzEt5OHgC7pJkuE-MXH_RnejR

# **Lista de Exercicios II - Estrutura de Decisão**

1 - O programa deverá informar se os valores podem ser
um triângulo. Indique, caso os lados formem um triângulo, se o mesmo é: equilátero, isósceles ou escaleno.
"""

lado1 = int(input("informe o lado 1 do triangulo: "))
lado2 = int(input("informe o lado 2 do triangulo: "))
lado3 = int(input("informe o lado 3 do triangulo: "))

if lado1 + lado2 > lado3  and  lado2 + lado3  > lado1  and  lado1 + lado3  > lado2 :
      if  lado1 == lado2 == lado3 :
            print ("Triângulo equilátero")
      elif  lado1  ==  lado2  or  lado2 == lado3 or lado1 == lado3 :
            print ("Triângulo isósceles")
      else:
             print  ("Triângulo escaleno")
else:
      print ("Não forma um triângulo")

"""2 - Verifique se  o ano é bissexto"""

ano = int(input("Digite qual ano você deseja saber se é bissexto : "))

if (ano % 4 == 0 and ano % 100 !=0) or ano % 400 == 0:
         print (ano, "foi/é ano bissexto")
else:
           print ("Não é ano bissexto")

"""3- Se haverá multa por quilos de peixes excedidos"""

peixes = int(input("Digite o peso de peixes: "))
multa = 4
if peixes > 50: 
  excesso = peixes - 50
  valor_multa = excesso * multa
  print("Quantidade que tem de excesso", excesso)
  print("João deve pagar um valor de R$", valor_multa)
else:
  print("João não precisa pagar multa")

"""4 - leia três números e mostre o maior deles"""

a = int(input("informe o valor de a: "))
b = int(input("informe o valor de b: "))
c = int(input("informe o valor de c: "))

if a > b and a > c:
  print("o maior valor é", a)
elif b > c:
  print("o maior valor é", b)
else:
  print("o maior valor é", c)

""" 5 - leia três números e mostre o maior e o menor deles"""

a = int(input("informe o valor de a: "))
b = int(input("informe o valor de b: "))
c = int(input("informe o valor de c: "))

if a > b and a > c:
  print("o maior valor é", a)
elif b > c:
  print("o maior valor é", b)
else:
  print("o maior valor é", c)

if a < b and a < c:
  print("o menor valor é", a)
elif b < c:
  print("o menor valor é", b)
else:
  print("o menor valor é", c)